In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)
pd.set_option("display.max_rows", 100)

In [3]:
# Update this path only if the CSV is moved to another location.
file_path = "Day10_Flight_Operations_Dataset.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully.")
print("Shape:", df.shape)
df.head()

Dataset loaded successfully.
Shape: (180, 17)

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3
1,FL0002,2026-06-07,Akasa Air,Delhi,Mumbai,Boeing 737,Economy,70,210,4468,0.0,On Time,Fog,Travel Agency,16,Vegan,5
2,FL0003,2026-05-12,Air India,Kochi,Delhi,Boeing 737,Economy,67,220,4713,5.0,On Time,Rain,Travel Agency,19,No Meal,2
3,FL0004,2026-05-30,Akasa Air,Srinagar,Delhi,Airbus A319,Economy,153,220,3791,35.0,Delayed,Storm,Travel Agency,18,No Meal,2
4,FL0005,2026-02-27,Air India,Pune,Delhi,Airbus A319,Premium Economy,178,180,6505,20.0,Delayed,Cloudy,Airline Website,25,No Meal,5

In [4]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types and non-null counts:")
df.info()

Number of rows: 180
Number of columns: 17

Column names:
['Flight_ID', 'Flight_Date', 'Airline', 'Origin', 'Destination', 'Aircraft', 'Travel_Class', 'Passengers', 'Seat_Capacity', 'Average_Ticket_Price', 'Delay_Minutes', 'Flight_Status', 'Weather', 'Booking_Channel', 'Avg_Baggage_Kg', 'Meal_Preference', 'Passenger_Satisfaction']

Data types and non-null counts:
<class 'pandas.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Flight_ID               180 non-null    str
 1   Flight_Date             180 non-null    str
 2   Airline                 180 non-null    str
 3   Origin                  180 non-null    str
 4   Destination             180 non-null    str
 5   Aircraft                180 non-null    str
 6   Travel_Class            180 non-null    str
 7   Passengers              180 non-null    int64
 8   Seat_Capacity           180 non-null    int64
 9   Average_Ticket_Price    180 non-null    int64
 10  Delay_Minutes           173 non-null    float64
 11  Flight_Status           180 non-null    str
 12  Weather                 180 non-null    str
 13  Booking_Channel         180 non-null    str
 14  Avg_Baggage_Kg          180 non-null    int64
 15  Meal_Preference         180 non-null    str
 16  Passenger_Satisfaction  180 non-null    int64
dtypes: float64(1), int64(5), str(11)
memory usage: 40.4 KB

In [5]:
print("First 5 records:")
display(df.head())

print("Last 5 records:")
display(df.tail())

First 5 records:

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3
1,FL0002,2026-06-07,Akasa Air,Delhi,Mumbai,Boeing 737,Economy,70,210,4468,0.0,On Time,Fog,Travel Agency,16,Vegan,5
2,FL0003,2026-05-12,Air India,Kochi,Delhi,Boeing 737,Economy,67,220,4713,5.0,On Time,Rain,Travel Agency,19,No Meal,2
3,FL0004,2026-05-30,Akasa Air,Srinagar,Delhi,Airbus A319,Economy,153,220,3791,35.0,Delayed,Storm,Travel Agency,18,No Meal,2
4,FL0005,2026-02-27,Air India,Pune,Delhi,Airbus A319,Premium Economy,178,180,6505,20.0,Delayed,Cloudy,Airline Website,25,No Meal,5

Last 5 records:

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
175,FL0176,2026-04-10,IndiGo,Ahmedabad,Bengaluru,Airbus A320,Economy,48,189,4298,0.0,On Time,Storm,Mobile App,11,Vegetarian,5
176,FL0177,2026-02-17,Vistara,Chennai,Mumbai,Airbus A320,Business,124,180,17306,20.0,Delayed,Cloudy,Mobile App,8,No Meal,5
177,FL0178,2026-04-30,IndiGo,Delhi,Mumbai,Airbus A319,Economy,112,186,4490,110.0,Delayed,Fog,Online Travel Portal,16,Vegetarian,3
178,FL0179,2026-05-08,Vistara,Bengaluru,Kochi,Airbus A320,Economy,134,189,5413,20.0,Delayed,Rain,Online Travel Portal,9,No Meal,2
179,FL0180,2026-01-22,Akasa Air,Delhi,Mumbai,Airbus A321,Economy,144,210,3767,75.0,Delayed,Fog,Online Travel Portal,17,No Meal,5

In [6]:
# Numerical summary
display(df.describe(include="all").T)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Flight_ID,180,180,FL0001,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Flight_Date,180,111,2026-02-10,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Airline,180,6,Vistara,37,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Origin,180,11,Delhi,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Destination,180,8,Delhi,51,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aircraft,180,4,Airbus A319,60,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Travel_Class,180,3,Economy,134,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Passengers,180.0,NaN,NaN,NaN,122.772222,45.635651,45.0,78.75,125.0,162.25,210.0
Seat_Capacity,180.0,NaN,NaN,NaN,197.238889,15.408176,180.0,186.0,189.0,210.0,220.0
Average_Ticket_Price,180.0,NaN,NaN,NaN,6111.677778,3615.22004,1949.0,3815.5,5380.0,6790.0,27832.0
Delay_Minutes,173.0,NaN,NaN,NaN,19.33526,29.029712,0.0,0.0,5.0,20.0,110.0
Flight_Status,180,3,On Time,114,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Weather,180,5,Rain,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Booking_Channel,180,4,Online Travel Portal,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Avg_Baggage_Kg,180.0,NaN,NaN,NaN,15.15,5.705506,5.0,10.0,15.5,20.0,25.0
Meal_Preference,180,4,Vegetarian,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Passenger_Satisfaction,180.0,NaN,NaN,NaN,3.494444,1.169908,2.0,2.0,3.0,5.0,5.0

In [7]:
missing = df.isnull().sum().sort_values(ascending=False)
missing_pct = (df.isnull().mean() * 100).sort_values(ascending=False)

missing_summary = pd.DataFrame({
    "Missing_Count": missing,
    "Missing_Percentage": missing_pct.round(2)
})

display(missing_summary)

print("Duplicate rows:", df.duplicated().sum())

                        Missing_Count  Missing_Percentage
Delay_Minutes                       7                3.89
Flight_ID                           0                0.00
Flight_Date                         0                0.00
Origin                              0                0.00
Airline                             0                0.00
Aircraft                            0                0.00
Travel_Class                        0                0.00
Passengers                          0                0.00
Destination                         0                0.00
Seat_Capacity                       0                0.00
Average_Ticket_Price                0                0.00
Flight_Status                       0                0.00
Weather                             0                0.00
Booking_Channel                     0                0.00
Avg_Baggage_Kg                      0                0.00
Meal_Preference                     0                0.00
Passenger_Satisfaction              0                0.00

Duplicate rows: 0

In [8]:
categorical_cols = df.select_dtypes(include=["object", "category"]).columns

for col in categorical_cols:
    print(f"\n--- {col} ---")
    print("Unique values:", df[col].nunique(dropna=True))
    display(df[col].value_counts(dropna=False).head(15))

--- Flight_ID ---
Unique values: 180

C:\Users\NISHANTH\AppData\Local\Temp\ipykernel_27104\2565180651.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=["object", "category"]).columns

Flight_ID
FL0001    1
FL0002    1
FL0003    1
FL0004    1
FL0005    1
FL0006    1
FL0007    1
FL0008    1
FL0009    1
FL0010    1
FL0011    1
FL0012    1
FL0013    1
FL0014    1
FL0015    1
Name: count, dtype: int64

--- Flight_Date ---
Unique values: 111

Flight_Date
2026-02-10    6
2026-06-23    5
2026-01-10    4
2026-03-09    3
2026-05-19    3
2026-01-08    3
2026-04-27    3
2026-03-12    3
2026-03-21    3
2026-03-07    3
2026-05-16    3
2026-04-30    3
2026-05-02    3
2026-04-23    3
2026-01-27    3
Name: count, dtype: int64

--- Airline ---
Unique values: 6

Airline
Vistara              37
SpiceJet             32
IndiGo               32
Akasa Air            31
Air India            24
Air India Express    24
Name: count, dtype: int64

--- Origin ---
Unique values: 11

Origin
Delhi        43
Mumbai       29
Bengaluru    21
Srinagar     15
Kochi        14
Ahmedabad    12
Pune         11
Lucknow      11
Chennai       9
Jaipur        8
Hyderabad     7
Name: count, dtype: int64

--- Destination ---
Unique values: 8

Destination
Delhi        51
Mumbai       30
Bengaluru    28
Kolkata      20
Chennai      17
Srinagar     13
Hyderabad    13
Kochi         8
Name: count, dtype: int64

--- Aircraft ---
Unique values: 4

Aircraft
Airbus A319    60
Boeing 737     44
Airbus A320    40
Airbus A321    36
Name: count, dtype: int64

--- Travel_Class ---
Unique values: 3

Travel_Class
Economy            134
Premium Economy     35
Business            11
Name: count, dtype: int64

--- Flight_Status ---
Unique values: 3

Flight_Status
On Time      114
Delayed       59
Cancelled      7
Name: count, dtype: int64

--- Weather ---
Unique values: 5

Weather
Rain      43
Cloudy    38
Fog       35
Clear     34
Storm     30
Name: count, dtype: int64

--- Booking_Channel ---
Unique values: 4

Booking_Channel
Online Travel Portal    50
Mobile App              45
Travel Agency           44
Airline Website         41
Name: count, dtype: int64

--- Meal_Preference ---
Unique values: 4

Meal_Preference
Vegetarian        52
Non-Vegetarian    45
Vegan             43
No Meal           40
Name: count, dtype: int64

In [9]:
# Select all numeric columns
numeric_cols = df.select_dtypes(include=np.number).columns.tolist()
print("Numeric columns:", numeric_cols)

if numeric_cols:
    print("\nSelected numeric columns:")
    display(df[numeric_cols].head())

Numeric columns: ['Passengers', 'Seat_Capacity', 'Average_Ticket_Price', 'Delay_Minutes', 'Avg_Baggage_Kg', 'Passenger_Satisfaction']

Selected numeric columns:

   Passengers  Seat_Capacity  Average_Ticket_Price  Delay_Minutes  Avg_Baggage_Kg  Passenger_Satisfaction
0         210            180                  6894           50.0              23                       3
1          70            210                  4468            0.0              16                       5
2          67            220                  4713            5.0              19                       2
3         153            220                  3791           35.0              18                       2
4         178            180                  6505           20.0              25                       5

In [10]:
# First 5 rows using iloc
display(df.iloc[:5])

# First 5 rows and first 3 columns
display(df.iloc[:5, :3])

# First 5 rows using loc
display(df.loc[df.index[:5]])

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3
1,FL0002,2026-06-07,Akasa Air,Delhi,Mumbai,Boeing 737,Economy,70,210,4468,0.0,On Time,Fog,Travel Agency,16,Vegan,5
2,FL0003,2026-05-12,Air India,Kochi,Delhi,Boeing 737,Economy,67,220,4713,5.0,On Time,Rain,Travel Agency,19,No Meal,2
3,FL0004,2026-05-30,Akasa Air,Srinagar,Delhi,Airbus A319,Economy,153,220,3791,35.0,Delayed,Storm,Travel Agency,18,No Meal,2
4,FL0005,2026-02-27,Air India,Pune,Delhi,Airbus A319,Premium Economy,178,180,6505,20.0,Delayed,Cloudy,Airline Website,25,No Meal,5

  Flight_ID Flight_Date    Airline
0    FL0001  2026-03-23   SpiceJet
1    FL0002  2026-06-07  Akasa Air
2    FL0003  2026-05-12  Air India
3    FL0004  2026-05-30  Akasa Air
4    FL0005  2026-02-27  Air India

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3
1,FL0002,2026-06-07,Akasa Air,Delhi,Mumbai,Boeing 737,Economy,70,210,4468,0.0,On Time,Fog,Travel Agency,16,Vegan,5
2,FL0003,2026-05-12,Air India,Kochi,Delhi,Boeing 737,Economy,67,220,4713,5.0,On Time,Rain,Travel Agency,19,No Meal,2
3,FL0004,2026-05-30,Akasa Air,Srinagar,Delhi,Airbus A319,Economy,153,220,3791,35.0,Delayed,Storm,Travel Agency,18,No Meal,2
4,FL0005,2026-02-27,Air India,Pune,Delhi,Airbus A319,Premium Economy,178,180,6505,20.0,Delayed,Cloudy,Airline Website,25,No Meal,5

In [11]:
# Example 1: filter rows where at least one numeric value is above its median.
# This demonstrates boolean filtering in a dataset-independent way.
if numeric_cols:
    filter_col = numeric_cols[0]
    threshold = df[filter_col].median()
    filtered = df[df[filter_col] > threshold]
    print(f"Filtering {filter_col} > median ({threshold}):")
    display(filtered.head(10))
else:
    print("No numeric columns are available for numeric filtering.")

Filtering Passengers > median (125.0):

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3
3,FL0004,2026-05-30,Akasa Air,Srinagar,Delhi,Airbus A319,Economy,153,220,3791,35.0,Delayed,Storm,Travel Agency,18,No Meal,2
4,FL0005,2026-02-27,Air India,Pune,Delhi,Airbus A319,Premium Economy,178,180,6505,20.0,Delayed,Cloudy,Airline Website,25,No Meal,5
6,FL0007,2026-06-17,Air India Express,Delhi,Srinagar,Airbus A319,Premium Economy,178,210,9430,0.0,On Time,Storm,Online Travel Portal,18,Vegetarian,4
7,FL0008,2026-04-28,Air India,Delhi,Chennai,Airbus A319,Business,157,220,14173,0.0,On Time,Fog,Airline Website,25,Vegan,5
10,FL0011,2026-04-17,Air India,Mumbai,Bengaluru,Airbus A321,Economy,195,189,3393,5.0,On Time,Clear,Airline Website,17,Vegetarian,2
12,FL0013,2026-05-14,SpiceJet,Pune,Delhi,Airbus A319,Economy,162,220,4689,0.0,On Time,Cloudy,Mobile App,6,Vegetarian,5
14,FL0015,2026-01-21,Akasa Air,Lucknow,Delhi,Boeing 737,Economy,133,186,3911,0.0,On Time,Cloudy,Travel Agency,21,No Meal,5
20,FL0021,2026-06-23,Vistara,Srinagar,Delhi,Airbus A320,Premium Economy,173,189,9018,0.0,On Time,Fog,Airline Website,14,Vegan,4
21,FL0022,2026-02-01,Vistara,Kochi,Delhi,Airbus A321,Economy,126,220,5887,75.0,Delayed,Clear,Airline Website,10,Vegetarian,2

In [12]:
# Example 2: filter a categorical column by its most common category.
if len(categorical_cols) > 0:
    filter_col = categorical_cols[0]
    common_value = df[filter_col].mode(dropna=True).iloc[0]
    filtered_cat = df[df[filter_col] == common_value]
    print(f"Filtering {filter_col} == {common_value!r}:")
    display(filtered_cat.head(10))
else:
    print("No categorical columns are available for categorical filtering.")

Filtering Flight_ID == 'FL0001':

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3

In [13]:
if numeric_cols:
    sort_col = numeric_cols[0]
    print(f"Top records by {sort_col}:")
    display(df.sort_values(by=sort_col, ascending=False).head(10))

    print(f"Bottom records by {sort_col}:")
    display(df.sort_values(by=sort_col, ascending=True).head(10))

Top records by Passengers:

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3
30,FL0031,2026-01-08,Vistara,Delhi,Srinagar,Airbus A321,Premium Economy,209,180,9962,50.0,Delayed,Cloudy,Mobile App,9,Vegetarian,4
92,FL0093,2026-04-30,Air India Express,Srinagar,Delhi,Airbus A319,Business,209,220,12970,0.0,On Time,Clear,Travel Agency,8,Vegan,2
148,FL0149,2026-02-10,Akasa Air,Jaipur,Mumbai,Airbus A319,Economy,202,210,6239,5.0,On Time,Rain,Online Travel Portal,8,No Meal,5
69,FL0070,2026-06-12,SpiceJet,Srinagar,Delhi,Boeing 737,Economy,201,189,2959,20.0,Delayed,Rain,Online Travel Portal,12,Vegan,4
153,FL0154,2026-04-09,Air India,Mumbai,Bengaluru,Airbus A321,Economy,201,186,3823,20.0,Delayed,Clear,Online Travel Portal,13,Vegan,2
29,FL0030,2026-04-10,SpiceJet,Delhi,Srinagar,Airbus A321,Economy,200,210,2716,75.0,Delayed,Storm,Airline Website,10,Vegan,3
94,FL0095,2026-06-14,Vistara,Bengaluru,Kochi,Airbus A319,Economy,199,189,4369,0.0,On Time,Fog,Online Travel Portal,11,Vegetarian,5
80,FL0081,2026-04-03,SpiceJet,Delhi,Mumbai,Airbus A320,Economy,199,180,2378,50.0,Delayed,Rain,Online Travel Portal,13,No Meal,4
107,FL0108,2026-05-30,IndiGo,Lucknow,Delhi,Airbus A319,Premium Economy,198,180,10551,75.0,Delayed,Rain,Travel Agency,13,Vegan,2

Bottom records by Passengers:

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
84,FL0085,2026-05-03,Air India,Lucknow,Delhi,Airbus A319,Economy,45,189,3299,35.0,Delayed,Rain,Online Travel Portal,21,Non-Vegetarian,3
78,FL0079,2026-03-21,Vistara,Mumbai,Kolkata,Airbus A320,Economy,45,186,4597,12.0,On Time,Rain,Online Travel Portal,25,No Meal,5
167,FL0168,2026-05-01,Air India,Delhi,Mumbai,Airbus A319,Economy,47,220,6479,0.0,On Time,Cloudy,Mobile App,18,Vegan,4
175,FL0176,2026-04-10,IndiGo,Ahmedabad,Bengaluru,Airbus A320,Economy,48,189,4298,0.0,On Time,Storm,Mobile App,11,Vegetarian,5
27,FL0028,2026-03-09,SpiceJet,Chennai,Mumbai,Boeing 737,Economy,49,220,3311,0.0,On Time,Clear,Online Travel Portal,17,Non-Vegetarian,2
53,FL0054,2026-04-11,SpiceJet,Mumbai,Bengaluru,Airbus A320,Economy,49,180,4738,20.0,Delayed,Rain,Mobile App,14,No Meal,3
143,FL0144,2026-02-25,Akasa Air,Mumbai,Bengaluru,Airbus A319,Economy,50,210,5522,12.0,On Time,Storm,Airline Website,25,Vegan,3
56,FL0057,2026-04-21,SpiceJet,Mumbai,Kolkata,Airbus A320,Premium Economy,51,189,10530,12.0,On Time,Rain,Mobile App,23,Vegetarian,3
11,FL0012,2026-03-30,Akasa Air,Lucknow,Delhi,Boeing 737,Economy,51,220,3046,5.0,On Time,Clear,Online Travel Portal,19,Non-Vegetarian,3
90,FL0091,2026-02-21,Vistara,Bengaluru,Kochi,Airbus A320,Economy,52,189,2251,0.0,On Time,Fog,Online Travel Portal,15,Non-Vegetarian,2

In [14]:
group_candidates = [
    c for c in categorical_cols
    if 1 < df[c].nunique(dropna=True) <= 30
]

if group_candidates and numeric_cols:
    group_col = group_candidates[0]
    agg_dict = {c: ["count", "mean", "min", "max"] for c in numeric_cols[:4]}

    grouped = df.groupby(group_col, dropna=False).agg(agg_dict)
    display(grouped)
else:
    print("Not enough suitable categorical/numeric columns for automatic aggregation.")

                  Passengers                      Seat_Capacity                       Average_Ticket_Price  \
                       count        mean min  max         count        mean  min  max                count
Airline
Air India                 24  128.083333  45  201            24  202.166667  180  220                   24
Air India Express         24  126.125000  57  209            24  194.041667  180  220                   24
Akasa Air                 31  110.548387  50  202            31  201.129032  180  220                   31
IndiGo                    32  129.937500  48  198            32  196.031250  180  220                   32
SpiceJet                  32  122.781250  49  210            32  194.593750  180  220                   32
Vistara                   37  121.189189  45  209            37  196.189189  180  220                   37

                                            Delay_Minutes
                          mean   min    max         count       mean  min    max
Airline
Air India          5083.083333  2516  14173            23  21.260870  0.0  110.0
Air India Express  7388.458333  2484  27832            24  11.291667  0.0  110.0
Akasa Air          5841.000000  2188  21499            30  14.400000  0.0   75.0
IndiGo             5931.656250  2552  15324            32  25.031250  0.0  110.0
SpiceJet           6189.750000  2378  16390            29  24.137931  0.0  110.0
Vistara            6265.648649  1949  17306            35  18.628571  0.0   75.0

In [15]:
if group_candidates:
    count_col = group_candidates[0]
    count_summary = (
        df.groupby(count_col, dropna=False)
          .size()
          .reset_index(name="Flight_Count")
          .sort_values("Flight_Count", ascending=False)
    )
    display(count_summary)

             Airline  Flight_Count
5            Vistara            37
3             IndiGo            32
4           SpiceJet            32
2          Akasa Air            31
1  Air India Express            24
0          Air India            24

In [16]:
# Create a copy before transformations
analysis_df = df.copy()

# Convert likely date/time columns to datetime when possible.
date_like_cols = [
    c for c in analysis_df.columns
    if any(key in c.lower() for key in ["date", "time", "day"])
]

converted_date_cols = []
for col in date_like_cols:
    converted = pd.to_datetime(analysis_df[col], errors="coerce")
    # Convert only if a reasonable number of values can be parsed.
    if converted.notna().sum() > 0:
        analysis_df[col] = converted
        converted_date_cols.append(col)

print("Converted date/time-like columns:", converted_date_cols)

Converted date/time-like columns: ['Flight_Date']

In [17]:
# Add simple derived features from the first usable datetime column.
if converted_date_cols:
    date_col = converted_date_cols[0]
    analysis_df["Analysis_Month"] = analysis_df[date_col].dt.month
    analysis_df["Analysis_Month_Name"] = analysis_df[date_col].dt.month_name()
    analysis_df["Analysis_Day_Name"] = analysis_df[date_col].dt.day_name()

    display(analysis_df[[date_col, "Analysis_Month_Name", "Analysis_Day_Name"]].head())
else:
    print("No usable date column was detected.")

  Flight_Date Analysis_Month_Name Analysis_Day_Name
0  2026-03-23               March            Monday
1  2026-06-07                June            Sunday
2  2026-05-12                 May           Tuesday
3  2026-05-30                 May          Saturday
4  2026-02-27            February            Friday

In [18]:
if numeric_cols:
    transform_col = numeric_cols[0]
    values = analysis_df[transform_col].dropna()

    if values.nunique() >= 3:
        analysis_df[f"{transform_col}_Band"] = pd.qcut(
            analysis_df[transform_col],
            q=3,
            labels=["Low", "Medium", "High"],
            duplicates="drop"
        )
        display(analysis_df[[transform_col, f"{transform_col}_Band"]].head(10))
    else:
        print(f"{transform_col} does not have enough unique values for banding.")

   Passengers Passengers_Band
0         210            High
1          70             Low
2          67             Low
3         153            High
4         178            High
5         123          Medium
6         178            High
7         157            High
8          82             Low
9         125          Medium

<h4>Question 1 — Which category has the most flight records?</h4>

In [19]:
if group_candidates:
    category_col = group_candidates[0]
    category_counts = (
        analysis_df[category_col]
        .value_counts(dropna=False)
        .rename_axis(category_col)
        .reset_index(name="Flight_Count")
    )
    display(category_counts.head(10))
    print("Most frequent category:", category_counts.iloc[0][category_col])

             Airline  Flight_Count
0            Vistara            37
1           SpiceJet            32
2             IndiGo            32
3          Akasa Air            31
4          Air India            24
5  Air India Express            24

Most frequent category: Vistara

<h4>Question 2 — Which category has the highest average numeric measure?</h4>

In [20]:
if group_candidates and numeric_cols:
    category_col = group_candidates[0]
    measure_col = numeric_cols[0]

    avg_by_category = (
        analysis_df.groupby(category_col, dropna=False)[measure_col]
        .mean()
        .sort_values(ascending=False)
        .reset_index(name=f"Average_{measure_col}")
    )
    display(avg_by_category.head(10))

             Airline  Average_Passengers
0             IndiGo          129.937500
1          Air India          128.083333
2  Air India Express          126.125000
3           SpiceJet          122.781250
4            Vistara          121.189189
5          Akasa Air          110.548387